services:
  runes:
    build:
      context: .
      args:
        WORKDIR: ${WORKDIR:-/runes}
    image: runes:latest
    ports:
      - 3000:3000
    volumes:
      - runes_node_modules:${WORKDIR:-/runes}/node_modules
      - runes_matron_build:${WORKDIR:-/runes}/packages/matron/build
      - .:${WORKDIR:-/runes}

volumes:
  runes_node_modules:
  runes_matron_build:
