name: continuous-integration
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container: midouest/runes:latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: |
          . /emsdk/emsdk_env.sh && \
          yarn configure-release && \
          yarn build-install
      - run: CI=true yarn test
