name: continuous-integration
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: midouest/runes:0.0.1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
